/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpSuitcase: typeof import('~icons/ep/suitcase')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
